@MonkeyBook.PostsApi_HostAddress = http://localhost:5233

POST {{MonkeyBook.PostsApi_HostAddress}}/post
Content-Type: application/json

{
  "monkeyId": "11111111-1111-1111-1111-111111111111",
  "message": "Hello from George!"
}

###
